apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp
spec:
  replicas: 5
  selector:
    matchLabels:
      name: goapp
  template:
    metadata:
      labels:
        name: goapp
        type: app
    spec:
      containers:
      - name: application
        image: s403o/goapp:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"